### ISSUE TITLE
dalao，输入一键脚本，出现这个问题

### ISSUE THREAD

**Issue by victoryLV** [marisn2017/ssrpanel#4]
Total size: 978 k
Total download size: 494 k
Downloading Packages:
screen-4.0.3-19.el6.x86_64.rpm                                                                                                                                                            | 494 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : screen-4.0.3-19.el6.x86_64                                                                                                                                                                    1/3 
  Updating   : wget-1.12-10.el6.x86_64                                                                                                                                                                       2/3 
  Cleanup    : wget-1.12-8.el6.x86_64                                                                                                                                                                        3/3 
  Verifying  : wget-1.12-10.el6.x86_64                                                                                                                                                                       1/3 
  Verifying  : screen-4.0.3-19.el6.x86_64                                                                                                                                                                    2/3 
  Verifying  : wget-1.12-8.el6.x86_64                                                                                                                                                                        3/3 

Installed:
  screen.x86_64 0:4.0.3-19.el6                                                                                                                                                                                   

Updated:
  wget.x86_64 0:1.12-10.el6                                                                                                                                                                                      

Complete!
不是以前输入博客地址的那个了

**Comment by 799953468** [comment]
等等就出来了

**Comment by 799953468** [comment]
wget --no-check-certificate https://raw.githubusercontent.com/marisn2017/ssrpanel/master/ssrpanel.sh&&chmod +x ssrpanel.sh&&bash ssrpanel.sh

**Comment by marisn2017** [comment]
感谢反馈~ @victoryLV
